name: "Build container"
on:
  push:
    tags:
      - v*
jobs:
  container:
    name: "Build container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Docker login"
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: "Build and push container"
        run: make docker
