name: "Run test suite"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - name: "Run tests"
        run: make test
