name: "Test and build"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "Test and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - name: "Download dependencies"
        run: make deps

      - name: "Compile project"
        run: make build

      - name: "Validate format"
        run: make fmt-ci

      - name: "Run tests"
        run: make test
