name: "Test and build"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "Test and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'

      - name: "Restore dependencies from cache"
        id: gomod-cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Download dependencies"
        if: steps.gomod-cache.outputs.cache-hit != 'true'
        run: make deps

      - name: "Compile project"
        run: make build

      - name: "Validate format"
        run: make fmt-ci

      - name: "Run tests"
        run: make test
